name: Deploy Frontend (Static Web Apps)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # DEBUG: show what the runner will deploy
      - name: Show app folder + staticwebapp.config.json
        run: |
          echo "PWD: $(pwd)"
          echo "Listing frontend/"
          ls -la frontend
          echo "---- staticwebapp.config.json (from frontend) ----"
          cat frontend/staticwebapp.config.json || true
          echo "--------------------------------------------------"

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: frontend
          output_location: ""
          # Force the action to use THIS config file:
          config_file_location: frontend/staticwebapp.config.json
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
