name: Deploy Backend (App Service)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: (Optional) Lint requirements exist
        run: test -f backend/requirements.txt

      # We DO NOT zip. We let Azure build from the backend folder.
      - name: Deploy to Azure Web App (with Oryx build)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ai-portfolio-backend     # exact App Service name (no suffix)
          package: backend                   # send the folder, not a zip
          enable-oryx-build: true            # tell Kudu to run Oryx (pip install)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}