name: Deploy Frontend (Static Web Apps)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "frontend/staticwebapp.config.json"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # No build: copy raw static files to build/
      - name: Prepare static site
        run: |
          rm -rf build
          mkdir -p build
          cp -r frontend/* build/

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "build"
          output_location: ""