name: Deploy Frontend (Static Web Apps)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # DEBUG: show token length + hash (safe to print)
      - name: Debug token (length + sha256/8)
        run: |
          echo -n '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}' | wc -c
          echo -n '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}' | sha256sum | cut -c1-8

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "frontend"
          output_location: ""
          production_branch: "main"   # <- explicitly tell SWA to use 'main'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        