name: Deploy Frontend (Static Web Apps)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Debug: print the config that will be deployed
      - name: Show app folder + config
        run: |
          echo "PWD: $(pwd)"
          ls -la frontend
          echo "----- staticwebapp.config.json -----"
          cat frontend/staticwebapp.config.json || true
          echo "-----------------------------------"

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: frontend
          output_location: ""
          config_file_location: frontend   # <-- FOLDER, not the file
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
