name: Deploy Frontend (Static Web Apps)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
      - "frontend/staticwebapp.config.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # We are not building anything. We just upload the 'frontend' folder.
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: frontend
          output_location: ""
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
