name: Deploy Frontend (Static Web Apps)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
      - "frontend/staticwebapp.config.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Copy the static site into a temporary build/ folder
      - name: Prepare static site
        run: |
          rm -rf build
          mkdir -p build
          cp -r frontend/* build/
          # ensure SWA config ships with the site
          if [ -f frontend/staticwebapp.config.json ]; then cp frontend/staticwebapp.config.json build/; fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "build"
          output_location: ""
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
