name: Deploy Frontend (Static Web Apps)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "frontend/staticwebapp.config.json"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sanity check so we fail early if the folder is wrong
      - name: Verify frontend folder
        run: |
          test -f frontend/index.html || (echo "frontend/index.html not found" && exit 1)
          ls -la frontend | head -n 30

      # Optional debug to confirm the secret made it to the runner
      - name: Debug token length + hash
        run: |
          echo -n '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}' | wc -c
          echo -n '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}' | sha256sum | cut -c1-8

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "frontend"     # we are uploading your existing static files
          output_location: ""
          production_branch: "main"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
